In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x=[[0,1],[5,1],[15,2],[25,5],[35,11],[45,15],[55,34],[60,33]]
y=[4,5,20,14,32,22,38,43]

In [3]:
x,y=np.array(x),np.array(y)

In [7]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 33]])

In [8]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [4]:
model=LinearRegression().fit(x,y)

In [5]:
r_sq=model.score(x,y)

In [6]:
print(f"coefficient of determination={r_sq}")

coefficient of determination=0.8603037137026477


In [9]:
print(f"intercept:{model.intercept_}")
print(f"scope:{model.coef_}")

intercept:5.415697339629158
scope:[0.4569043  0.24526853]


In [10]:
#predict result
y_pred=model.predict(x)
print(f"predicted response:/n{y_pred}")

predicted response:/n[ 5.66096587  7.94548735 12.75979884 18.0646474  24.10530155 29.65541863
 38.88456371 40.92381665]


In [11]:
y_pred=model.intercept_+np.sum(model.coef_*x,axis=1)

In [12]:
print(f"predictedresponse:/n{y_pred}")

predictedresponse:/n[ 5.66096587  7.94548735 12.75979884 18.0646474  24.10530155 29.65541863
 38.88456371 40.92381665]


In [13]:
x_new=np.arange(10).reshape((-1,2))
y_new=model.predict(x_new)

In [14]:
x_new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
y_new

array([ 5.66096587,  7.06531153,  8.46965718,  9.87400284, 11.2783485 ])