In [1]:
import pandas as pd
a1=pd.Series([1,2,3,4])
print(a1)

0    1
1    2
2    3
3    4
dtype: int64


In [2]:
import pandas as pd
a2=pd.DataFrame([1,12,3,4,5])
print(a2)

    0
0   1
1  12
2   3
3   4
4   5


In [3]:
import numpy as np
arr=np.array([15,12,14])
print(arr)

[15 12 14]


In [4]:
import numpy as np
arr=np.copy([1,2,35,6,8])
print(arr)

[ 1  2 35  6  8]


In [14]:
import numpy as np
arr=np.stack([1,2,35,6,8])
print(arr)

[ 1  2 35  6  8]


In [6]:
import numpy as np
arr=np.shape([1,2,35,6,8])
print(arr)

(5,)


In [13]:
import numpy as np
arr=np.vstack([1,2,35,6,8])
print(arr)

[[ 1]
 [ 2]
 [35]
 [ 6]
 [ 8]]


In [10]:
import numpy as np
arr=np.dstack([1,2,35,6,8])
print(arr)

[[[ 1  2 35  6  8]]]


In [40]:
import numpy as np
arr=np.array([1,2,35,6,8])
print(arr)

[ 1  2 35  6  8]


In [19]:
import numpy as np
print(np.__version__)

1.16.5


In [20]:
import numpy as np
arr=np.copy([1,2,35,6,8])
print(arr)
print(type(arr))

[ 1  2 35  6  8]
<class 'numpy.ndarray'>


In [21]:
import numpy as np
arr=np.copy([1,2,35,6,8])
print(arr)
print(arr.ndim)

[ 1  2 35  6  8]
1


In [23]:
import numpy as np
arr=np.array([1,2,35,6,8])
print(arr[0])

1


In [25]:
import numpy as np
arr=np.array([1,2,35,6,8])
print(arr[0])
print(arr[2]+arr[4])


1
43


In [32]:
import numpy as np
arr=np.array([1,2,35,6,8])
print(arr[1:4])

[ 2 35  6]


In [33]:
import numpy as np
arr=np.array([1,2,35,6,8])
print(arr[4:])
print(arr[:4])
print(arr[1:4:2])

[8]
[ 1  2 35  6]
[2 6]


In [34]:
import numpy as np
arr=np.array([1,2,35,6,8])
x=arr.view()
print(arr)
print(x)

[ 1  2 35  6  8]
[ 1  2 35  6  8]


In [39]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=arr.reshape(4,3)
print(arr)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
