In [19]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [20]:
from sklearn.preprocessing import PolynomialFeatures

In [24]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([15,11,2,8,25,32])

In [26]:
x 

array([ 5, 15, 25, 35, 45, 55])

In [27]:
y

array([15, 11,  2,  8, 25, 32])

In [33]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([15,11,2,8,25,32])

In [34]:
transformer=PolynomialFeatures(degree=2,include_bias=False)
transformer.fit(x,y)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False,
                   order='C')

In [35]:
x_=transformer.transform(x)

In [36]:
#x_=PolynomialFeatures()(degree=2,include_bias=False)transformer.fit(x,y)
model=LinearRegression().fit(x_,y)

In [37]:
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [38]:
r_sq=model.score(x_,y)
print(f"coefficient of determination:{r_sq}")
print(f"intercept:{model.intercept_}")
print(f"scope:{model.coef_}")

coefficient of determination:0.8908516262498564
intercept:21.372321428571453
scope:[-1.32357143  0.02839286]


In [39]:
y_pred=model.predict(x_)
print(f"predicted response:/n{y_pred}")

predicted response:/n[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]
